### ISSUE TITLE
Hands-On: Add TDD example

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/tutorial-management#21]
This will involve both code and instructions.

**Comment by bernhold** [comment]
See also https://github.com/bssw-tutorial/presentations/issues/22

and comments therein about lack of evidence that TDD is beneficial

**Comment by frobnitzem** [comment]
The draft hands-on material I created for this was documentation-driven-design.  I've had a lot of personal success with that method, since it forces you to "write down requirements and documentation" before getting lost in the implementation details.  As for test-driven-design, I hedged a bit by noting that the tests and code should develop in-step.

**Comment by bernhold** [comment]
@frobnitzem I think your strategy is probably more realistic and more appropriate than a strict TDD approach.  Others are welcome to comment, however.

**Comment by bernhold** [comment]
Done by Greg for SC21.
